Change FE base image

diff --git a/docker/fe/Dockerfile b/docker/fe/Dockerfile
--- a/docker/fe/Dockerfile
+++ b/docker/fe/Dockerfile
@@ -1,4 +1,4 @@
-FROM openjdk:8
+FROM centos:7.6.1810
 
 LABEL maintainer="zhoufeng@hujiang.com"
 
@@ -8,8 +8,19 @@ RUN echo Asia/Shanghai > /etc/timezone
 
 ENV PALO_CONTAINER true
 
+RUN for iter in {1..10}; do yum update -y && \
+    yum install -y nc && \
+    yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; done; \
+    (exit $exit_code)
+
+ADD jdk-8u212-linux-x64.tar.gz /usr/java
+RUN ln -s /usr/java/jdk1.8.0_212/ /usr/java/jdk
+ENV JAVA_HOME /usr/java/jdk
+ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
+ENV PATH $PATH:$JAVA_HOME/bin
+
 RUN groupadd -g 1000 palo && \
-    useradd -u 1000 -g 1000 -d /usr/share/palo -m palo && \
+    adduser -u 1000 -g 1000 -G 0 -d /usr/share/palo palo && \
     chmod 0775 /usr/share/palo && \
     chgrp 0 /usr/share/palo
 
